config/routes.rb
DemoSearch::Application.routes.draw do
  root to: 'static_pages#home'

  match '/home',         to: 'static_pages#home'
  match '/help',         to: 'static_pages#help'
  match '/addkeyword',   to: 'static_pages#add_keyword'
  match '/listkeywords', to: 'static_pages#list_all_keywords'
  match '/about',        to: 'static_pages#about'
  match '/contact',      to: 'static_pages#contact'
  match '/result',       to: 'static_pages#result'
  match '/details',      to: 'static_pages#details'
  match '/ontology',     to: 'static_pages#ontology'
  match '/display_all_genes', to: 'static_pages#display_all_genes'
  match '/popup_ontology', to: 'static_pages#popup_ontology'
  match '/cytoscape_web', to: 'static_pages#cytoscape_web'

  resources :static_pages do
    get :autocomplete_key_word_set_keyword, :on => :collection
  end

end

app/models/key_word_set.rb
class KeyWordSet < ActiveRecord::Base
  attr_accessible :keyword

  validates :keyword, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
require 'net/http'
require 'json'
require 'will_paginate/array'

class StaticPagesController < ApplicationController
  autocomplete :key_word_set, :keyword, :limit => 5

  before_filter :pre_ontology, only: :ontology

  def home
    @anchors = {}
    letters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
    letters.each{ |letter| @anchors[letter] = 0 } 

    @search_tem = ""
    @query_result = []

    if params.has_key?(:search)
      session[:search_keyword] = params[:search][:keyword]
      escape_keyword = URI.escape(params[:search][:keyword])
      json_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/terms?name=" + escape_keyword + "&format=JSON&limit=-1"))
      @search_term = params[:search][:keyword]
      @query_result = ActiveSupport::JSON.decode(json_result)
      # @static_pages = @query_result.paginate(page: params[:page])
    elsif params.has_key?(:page)
      escape_keyword = URI.escape(session[:search_keyword])
      json_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/terms?name=" + escape_keyword + "&format=JSON&limit=-1"))
      @search_term = session[:search_keyword]
      @query_result = ActiveSupport::JSON.decode(json_result)
      # @static_pages = @query_result.paginate(page: params[:page])
    end

    @exact_match = [] 
    @other_hits = []

    @query_result.each do |keyword|
      if @search_term.downcase == keyword["value"].downcase
        @exact_match.push(keyword["value"])
      else
        @other_hits.push(keyword["value"])
      end
    end
  end

  def result
    # @query_result = KeyWordSet.find_by_keyword(params[:search][:keyword])
    # @query_result = KeyWordSet.where("lower(keyword) LIKE ?", "%#{params[:search][:keyword].downcase}%")
  end

  def details
    @select_term = params[:select_term]
    session[:select_term] = params[:select_term]
    @select_ontology = params[:select_ontology]
    session[:select_ontology] = params[:select_ontology]

    escape_select_term = URI.escape(params[:select_term])
    escape_select_ontology = URI.escape(params[:select_ontology])
    json_details_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/terms_details?name=" + escape_select_term + "&ontology=" + escape_select_ontology))
    @details_result = ActiveSupport::JSON.decode(json_details_result)

    @details_result.each do |item|
      if item["label"] == "ontologyid"
        @ontology_id = item["value"]
      elsif item["label"] == "ontologyName"
        @ontology_name = item["value"]
      elsif item["label"] == "termid"
        @term_id = item["value"]
      elsif item["label"] == "termName"
        @term_name = item["value"]
      elsif item["label"] == "bioportalURL"
        @bioportal_url = item["value"]
      elsif item["label"] == "genes"
        @gene_list = item["value"]
      elsif item["label"] == "numberOfGenes"
        @num_of_genes = item["value"]
      elsif item["label"] == "AUC"
        @auc = item["value"]
      end
    end

    if @num_of_genes <= 100
      index = 0
      @genes = ""
      @genes_for_yql = ""
      @gene_list.each do |gene|
        if index == 0
          @genes.concat(gene[1])
          @genes_for_yql.concat(gene[1])
        else
          @genes.concat("|" + gene[1])
          @genes_for_yql.concat("%7C" + gene[1])
        end
        index = index + 1
      end
    end

    # render :layout => "show_cytoscape"
    render layout: false
  end

  def ontology
    @term_name = params[:term_name]
    escape_term_name = URI.escape(params[:term_name])
    ontology_json_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/get_ontologies?termname=" + escape_term_name))
    @ontology_results = ActiveSupport::JSON.decode(ontology_json_result)
    render layout: false
  end

  def display_all_genes
    escape_select_term = URI.escape(session[:select_term])
    escape_select_ontology = URI.escape(session[:select_ontology])
    json_details_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/terms_details?name=" + escape_select_term + "&ontology=" + escape_select_ontology))
    @details_result = ActiveSupport::JSON.decode(json_details_result)

    @details_result.each do |item|
      if item["label"] == "genes"
        @gene_list = item["value"]
      end
    end      
    render layout: false
  end

  def cytoscape_web
    escape_select_term = URI.escape(session[:select_term])
    escape_select_ontology = URI.escape(session[:select_ontology])
    networks_str = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/getNetworks?name=" + escape_select_term + "&ontology=" + escape_select_ontology))
    network_weights_str = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/getNetworkWeights?name=" + escape_select_term + "&ontology=" + escape_select_ontology))

    json_details_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/terms_details?name=" + escape_select_term + "&ontology=" + escape_select_ontology))
    @details_result = ActiveSupport::JSON.decode(json_details_result)
    @details_result.each do |item|
      if item["label"] == "genes"
        @gene_list = item["value"]
        break
      end
    end

    @gene_hash = {}
    @gene_list.each do |gene|
      @gene_hash[gene[0]] = gene[1]
    end

    @get_networks = []
    networks_list = networks_str.split(/\n/)
    networks_list.each do |line|
      single_network = line.split(/\t+/)
      @get_networks << single_network
    end 

    pre_network_weight = ""
    @network_weight_key = ""
    @network_weights_hash = {}
    @get_network_weights = []
    sub_network_weights = []
    network_weights_list = network_weights_str.split(/\n/)
    network_weights_list.each do |line|
      if not line.match(/^\t/)
        if pre_network_weight != ""
          @network_weights_hash[pre_network_weight] = sub_network_weights
          sub_network_weights = []
        end
        single_network_weight = line.split(/\t+/)
        @get_network_weights << single_network_weight
        pre_network_weight = single_network_weight[0]
      else
        single_subnetwork_weight = line.split(/\t+/)
        single_subnetwork_weight.slice!(0)
        sub_network_weights << single_subnetwork_weight
      end
    end
    @network_weights_hash[pre_network_weight] = sub_network_weights
    render layout: false
  end

  def help
  end

  def add_keyword
    @add = KeyWordSet.new(params[:add])
    if @add.save
      flash[:success] = "Add successfully!"
      redirect_to "/addkeyword" and return
    else
      render 'add_keyword'
    end
  end

  def list_all_keywords
    @keywords = KeyWordSet.all
  end

  def about
  end

  def contact
  end

  private

    def pre_ontology
      @term_name = params[:term_name]
      escape_term_name = URI.escape(params[:term_name])
      ontology_json_result = Net::HTTP.get(URI.parse("http://rest.mooneygroup.org/get_ontologies?termname=" + escape_term_name))
      @ontology_results = ActiveSupport::JSON.decode(ontology_json_result)

      if @ontology_results.length == 1
        redirect_to details_path(:select_ontology => @ontology_results[0]["value"], :select_term => @term_name)
      else
        render :partial => "facebox_popup"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Stop Search"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_cytoscape_script.html.erb
<script type="text/javascript">
  window.onload=function() {
    var div_id = "cytoscapeweb";

    var networ_json = {
      dataSchema: {
        nodes: [ { name: "label", type: "string" } ]
      },
      data: {
        nodes: [ { id: "1", label: "1" }, { id: "2", label: "2" } ],
        edges: [ { id: "2to1", target: "1", source: "2" } ]
      }
    };

    var options = {
      swfPath: "<%= asset_path("swf/CytoscapeWeb") %>",
      flashInstallerPath: "<%= asset_path("swf/playerProductInstall") %>"
    };

    var vis = new org.cytoscapeweb.Visualization(div_id, options);
    vis.draw({ network: networ_json });
  };
</script>

app/views/layouts/_facebox.html.erb
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $(".show_ontology").click(function (event) {
      term_name = $(this).attr('term_name');
      escape_term_name = escape(term_name);
      url = "http://rest.mooneygroup.org/get_ontologies?termname=" + escape_term_name + "&callback=?";

      $.getJSON(url, function(ontology_json) {
        ontology_array = $.parseJSON(JSON.stringify(ontology_json));

        if (ontology_array.length == 1) {
          escape_ontology_name = escape(ontology_array[0]["value"]);
          window.location.href = "/details?select_ontology=" + escape_ontology_name + "&select_term=" + escape_term_name;
        } else {
          // facebox_source = "<ul class=\"nav nav-list\"><li><p class=\"muted\">The term <strong>" + term_name + "</strong> has been found in multiple ontologies. Please select the ontology: </p></li><li class=\"divider\">";

          facebox_source = "The term <strong>" + term_name + "</strong> has been found in multiple ontologies. Please select the ontology: <hr><ul>";

          $.each(ontology_array, function (index, value) {
            escape_ontology_name = escape(value["value"]);
            facebox_source += "<li><a href=/details?select_ontology=" + escape_ontology_name + "&select_term=" + escape_term_name + ">" + value["value"] + "</a></li>";
          });

          facebox_source += "</li></ul>";

          $.facebox(facebox_source);
        }
      });

      event.preventDefault();
    });

    $('a[rel*=facebox]').facebox({
      loadingImage : '/assets/loading.gif',
      closeImage   : '/assets/closelabel.png'
    })
  })
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed and Designed by Skinner
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar less">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "jquery-1.9.1.min.js", "jquery-migrate-1.1.1.min.js", "jquery-ui-1.10.1.custom.min.js", "autocomplete-rails.js", "facebox.js" %>
  <%= javascript_include_tag "http://mooneygroup.org/bar/mooney-top-nav.js" %>
  <%= render 'layouts/facebox' %>
  <%= stylesheet_link_tag "jquery-ui-1.10.1.custom.css", "facebox.css" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/show_cytoscape.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "jquery-1.9.1.min.js", "jquery-migrate-1.1.1.min.js", "jquery-ui-1.10.1.custom.min.js", "autocomplete-rails.js" %>
  <%= javascript_include_tag "json2.min.js", "AC_OETags.min.js", "cytoscapeweb.min.js" %>
  <%= render 'layouts/cytoscape_script' %>
  <%= stylesheet_link_tag "cytoscape_web.css" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/_anchor_letter.html.erb
<div class="pagination pagination-small pagination-centered">
  <ul>
    <li><a href="#A">A</a></li>
    <li><a href="#B">B</a></li>
    <li><a href="#C">C</a></li>
    <li><a href="#D">D</a></li>
    <li><a href="#E">E</a></li>
    <li><a href="#F">F</a></li>
    <li><a href="#G">G</a></li>
    <li><a href="#H">H</a></li>
    <li><a href="#I">I</a></li>
    <li><a href="#J">J</a></li>
    <li><a href="#K">K</a></li>
    <li><a href="#L">L</a></li>
    <li><a href="#M">M</a></li>
    <li><a href="#N">N</a></li>
    <li><a href="#O">O</a></li>
    <li><a href="#P">P</a></li>
    <li><a href="#Q">Q</a></li>
    <li><a href="#R">R</a></li>
    <li><a href="#S">S</a></li>
    <li><a href="#T">T</a></li>
    <li><a href="#U">U</a></li>
    <li><a href="#V">V</a></li>
    <li><a href="#W">W</a></li>
    <li><a href="#X">X</a></li>
    <li><a href="#Y">Y</a></li>
    <li><a href="#Z">Z</a></li>
  </ul>
</div>

app/views/static_pages/_results.html.erb
<hr>

<div class="alert alert-success">
  <h3>Exact match</h3>
</div>

<% if !@exact_match.empty? %>
  <ul>
    <li>
      <div class="show_ontology" term_name="<%= @exact_match[0] %>">
      <h4><%= link_to @exact_match[0], ontology_path(:term_name => @exact_match[0]) %></h4>
      </div>
    </li>
  </ul>
<% else %>
  <p class="lead text-error text-center">Nothing Found</p>
<% end %>

<hr>

<div class="alert alert-block">
  <h3>Other hits</h3>
</div>

<% if !@other_hits.empty? %>
  <%= render 'anchor_letter' %>

  <ul>
    <% @other_hits.each do |keyword| %>
      <li>
        <% if @anchors[keyword[0].upcase] == 0 %>
          <div class="show_ontology" term_name="<%= keyword %>">
          <h4><%= link_to keyword, ontology_path(:term_name => keyword), :"term_name" => keyword, :name => keyword[0].upcase %></h4>
          </div>
          <% @anchors[keyword[0].upcase] = 1 %>
        <% else %>
          <div class="show_ontology" term_name="<%= keyword %>">
          <h4><%= link_to keyword, ontology_path(:term_name => keyword), :"term_name" => keyword %></h4>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="lead text-error text-center">Nothing Found</p>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  This demo is about the first milestone.
</p>

app/views/static_pages/add_keyword.html.erb
<div class="center hero-unit">
  <h1>Add the Keyword</h1>
</div>

<div class="center row">
  <div class="span6 offset3">
    <%= form_for(:add) do |f| %>
      <%= f.text_field :keyword %>
      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Email: skinner.cheng@gmail.com
</p>

app/views/static_pages/details.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "http://mooneygroup.org/bar/mooney-top-nav.js" %>
  <%= javascript_include_tag "jquery-1.9.1.min.js", "jquery-migrate-1.1.1.min.js" %>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".show_more_genes").click(function (event) {
        $('#more_genes').hide();
        $('#hide_genes').show();
        $('#remaining_genes').show();
        event.preventDefault();
      });
      $(".hide_more_genes").click(function (event) {
        $('#more_genes').show();
        $('#hide_genes').hide();
        $('#remaining_genes').hide();
        event.preventDefault();
      });
      /*
      $(".show_more_genes_2").click(function (event) {
        $('#more_genes_2').hide();
        $('#hide_genes_2').show();
        $('#remaining_genes_2').show();
        event.preventDefault();
      });
      $(".hide_more_genes_2").click(function (event) {
        $('#more_genes_2').show();
        $('#hide_genes_2').hide();
        $('#remaining_genes_2').hide();
        event.preventDefault();
      });
      */
      /*
      doYQL("http://genemania.org/search/human/<%= @genes_for_yql %>");
      function doYQL(site) {
        var yql = 'http://query.yahooapis.com/v1/public/yql?q=' + encodeURIComponent('select * from html where url="' + site + '"');
        $.ajax({
          url: yql,
          type: "GET",
          dataType: "html",
          success: function(xml) {
            info = $(xml).find('results').html();
            // console.log(info);
            // $('#loadingImag').remove();
            // $('#network_visualization').html(info);
          },
          error: function(xhr, ajaxOptions, thrownError) {
            // alert(thrownError);
          }
        });
      }
      */
    });
  </script>
  <style>
    html, body { height: 100%; width: 100%; padding: 0; margin: 0; }
    #details_list { width: 20%; height: 100%; float: left; }
    #network_visualization { width: 80%; height: 100%; float: right; }
  </style>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
  <body>
    <div id="details_list" style="overflow-x:hidden; overflow-y:scroll;">
      <div class="navbar">
        <div class="navbar-inner">
          <ul class="nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <% if @num_of_genes >= 5 && @num_of_genes <= 100 %>
              <li><%= link_to "Skinner", cytoscape_web_path, target: '_blank' %></li>
            <% end %>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </div>
      </div>
      <div style="padding:0 10px"><dl>
        <dt>Term</dt><dd><%= @term_name %></dd> 
        <dt>Term id</dt><dd><%= @term_id %></dd>
        <dt>Ontology</dt><dd><%= @ontology_name %></dd>
        <dt>Ontology id</dt><dd><%= @ontology_id %></dd>
        <dt>Bioportal</dt><dd><%= link_to "Click Here", @bioportal_url, :target => '_blank' %></dd>
        <% if @auc.nil? %>
          <dt>AUC</dt><dd>N/A</dd>
        <% else %>
          <dt>AUC</dt><dd><%= @auc %></dd>
        <% end %>
        <dt>Number of Genes</dt><dd><%= @num_of_genes %></dd>
        <dt>List of Genes</dt>
        <dd>
        <!--
        <%= link_to "Display All", display_all_genes_path(), :rel => "facebox" %>
        -->
        </dd>
      </dl></div>
      <table class="table table-condensed">
        <tr><td width=50%><strong>Gene Name</strong></td><td width=50%><strong>Gene ID</strong></td></tr>
        <% if @gene_list.length > 100 %>
          <% @gene_list[0..99].each do |gene| %>
            <tr><td width=50%><%= gene[1] %></td><td width=50%><%= gene[0] %></td></tr>
          <% end %>
        <% else %>
          <% @gene_list.each do |gene| %>
            <tr><td width=50%><%= gene[1] %></td><td width=50%><%= gene[0] %></td></tr>
          <% end %>
        <% end %>
      </table>
      <div id="remaining_genes" style="display: none;">
        <% if @gene_list.length > 100 %>
          <table class="table table-condensed">
            <% @gene_list[100..-1].each do |gene| %>
              <tr><td width=50%><%= gene[1] %></td><td width=50%><%= gene[0] %></td></tr>
            <% end %>
          </table>
        <% end %>
      </div>
      <div id="more_genes" class="show_more_genes">
        <% if @gene_list.length > 100 %>
          <p class="text-center">
          <%= link_to "More ( " + (@gene_list.length - 100).to_s + " genes total )" %>
          </p>
        <% end %>
      </div>
      <div id="hide_genes" class="hide_more_genes" style="display: none;">
        <p class="text-center">
        <%= link_to "Hide ( " + (@gene_list.length - 100).to_s + " genes total )" %>
        <p>
      </div>
      <!--
      <hr>
      <% @gene_list.each.with_index do |gene, index| %>
        <% if index <= 100 %>
          <%= gene[1] %> (<%= gene[0] %></td>), 
        <% end %>
      <% end %>
      <div id="remaining_genes_2" style="display: none;">
        <% @gene_list.each.with_index do |gene, index| %>
          <% if index > 100 %>
            <%= gene[1] %> (<%= gene[0] %></td>),
          <% end %>
        <% end %>
      </div>
      <div id="more_genes_2" class="show_more_genes_2">
        <% if @gene_list.length > 100 %>
          <p class="text-center">
          <%= link_to "More ( " + (@gene_list.length - 100).to_s + " genes total )" %>
          </p>
        <% end %>
      </div>
      <div id="hide_genes_2" class="hide_more_genes_2" style="display: none;">
        <p class="text-center">
        <%= link_to "Hide ( " + (@gene_list.length - 100).to_s + " genes total )" %>
        <p>
      </div>
      -->
    </div>
    <div id="network_visualization" style="overflow: hidden; position: relative;">
      <% if @num_of_genes <= 100 %>
        <iframe id="genemania_network_visualization" src="http://genemania.org/search/human/<%= @genes %>&m=automatic&r=0" style="width: 100%; height:111%; position: absolute; top: -81px;"></iframe>
      <% else %>
        <br><br><br><br><br>
        <div class="container">
          <div class="alert alert-error">
            <p class="lead text-center">Won't display the network visualization because the number of genes exceeds 100.</p>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/static_pages/display_all_genes.html.erb
<table class="table table-condensed">
  <tr><td><strong>Gene Name</strong></td><td><strong>Gene ID</strong></td><td><strong>Gene Name</strong></td><td><strong>Gene ID</strong></td><td><strong>Gene Name</strong></td><td><strong>Gene ID</strong></td></tr>
    <% @gene_list.each.with_index do |gene, index| %>
      <% if index % 3 == 0 %>
        <tr><td><%= gene[1] %></td><td><%= gene[0] %></td>
      <% elsif index % 3 == 1 %>
        <td><%= gene[1] %></td><td><%= gene[0] %></td>
      <% elsif index % 3 == 2 %>
        <td><%= gene[1] %></td><td><%= gene[0] %></td></tr>
      <% end %>
    <% end %>
</table>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>STOP</h1>
  <blockquote class="pull-right">Statistical Tracking of Ontological Phrases</blockquote>
</div>

<div class="center row">
  <div class="span6 offset3">
    <%= form_for(:search, url: "home") do |f| %>
      <%= f.text_field :keyword, class: "input-large search-query", :'data-autocomplete' => "static_pages/autocomplete_key_word_set_keyword"  %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= render 'results' if !@query_result.empty?  %>

app/views/static_pages/list_all_keywords.html.erb
<div class="center hero-unit">
  <h1>List All the Keywords</h1>
</div>

<ul>
  <% @keywords.each do |keywordset| %>
    <li>
      <%= keywordset.keyword %>
    </li>
  <% end %>
</ul>

app/views/static_pages/ontology.html.erb
<ul class="nav nav-list">
  <li><p class="muted">The term <strong><%= @term_name %></strong> has been found in multiple ontologies. Please select the ontology: </p></li>
  <li class="divider"></li> 

  <% @ontology_results.each do |ontology_name| %>
    <li>
      <%= link_to ontology_name["value"], details_path(:select_ontology => ontology_name["value"], :select_term => @term_name) %>
    </li>
  <% end %> 
</ul>

app/views/static_pages/popup_ontology.html.erb
<ul class="nav nav-list">
  <li>The term <strong><%= @term_name %></strong> has been found in multiple ontologies. Please select the ontology: </li>

  <% @ontology_results.each do |ontology_name| %>
    <li>
      <%= link_to ontology_name["value"], details_path(:select_ontology => ontology_name["value"], :select_term => @term_name) %>
    </li>
  <% end %> 
</ul>

app/views/static_pages/result.html.erb
<div class="center hero-unit">
  <h1>Query Result</h1>
</div>

<ul>
  <% @query_result.each do |keyword| %>
    <li>
      <%= keyword["value"] %>
    </li>
  <% end %>
</ul>